create table if not exists public.ai_rate_limit_events (
  id bigint generated by default as identity primary key,
  identifier text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists ai_rate_limit_events_identifier_created_at_idx
  on public.ai_rate_limit_events (identifier, created_at desc);

alter table public.ai_rate_limit_events enable row level security;

create policy "service role can manage ai rate limit events"
  on public.ai_rate_limit_events
  as permissive
  for all
  to service_role
  using (true)
  with check (true);
